// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210808150235_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Shared.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Genk",
                            Name = "IT"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Tongeren",
                            Name = "HR"
                        },
                        new
                        {
                            Id = 3,
                            Location = "Hasselt",
                            Name = "Production"
                        });
                });

            modelBuilder.Entity("Shared.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMarried")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2003, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Description = "Description of John",
                            Email = "John@test.com",
                            FirstName = "John&",
                            Gender = 0,
                            ImageUrl = "https://via.placeholder.com/150",
                            IsMarried = false,
                            LastName = "Winter",
                            Salary = 2500.5678m
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(2004, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Description = "Description of Sam",
                            Email = "Sam@test.com",
                            FirstName = "Sam",
                            Gender = 0,
                            ImageUrl = "https://via.placeholder.com/150",
                            IsMarried = false,
                            LastName = "Winter",
                            Salary = 2500.5678m
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(2004, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Description = "Description of Ceyn",
                            Email = "Ceyn@test.com",
                            FirstName = "Ceyn",
                            Gender = 1,
                            ImageUrl = "https://via.placeholder.com/150",
                            IsMarried = true,
                            LastName = "Winter",
                            Salary = 2500.5678m
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(2004, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Description = "Description of Donald",
                            Email = "Donald@test.com",
                            FirstName = "Donald",
                            Gender = 0,
                            ImageUrl = "https://via.placeholder.com/150",
                            IsMarried = false,
                            LastName = "Winter",
                            Salary = 2500.5678m
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(2004, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Description = "Description of Tom",
                            Email = "John@test.com",
                            FirstName = "Tom",
                            Gender = 0,
                            ImageUrl = "https://via.placeholder.com/150",
                            IsMarried = false,
                            LastName = "Zomer",
                            Salary = 2500.5678m
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(2004, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Description = "Description of Hans",
                            Email = "Sam@test.com",
                            FirstName = "Hans",
                            Gender = 0,
                            ImageUrl = "https://via.placeholder.com/150",
                            IsMarried = false,
                            LastName = "Winter",
                            Salary = 2500.5678m
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateTime(2004, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Description = "Description of Ceyn",
                            Email = "Ceyn@test.com",
                            FirstName = "Mark",
                            Gender = 1,
                            ImageUrl = "https://via.placeholder.com/150",
                            IsMarried = true,
                            LastName = "Winter",
                            Salary = 2500.5678m
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateTime(2004, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Description = "Description of Donald",
                            Email = "Donald@test.com",
                            FirstName = "Roni",
                            Gender = 0,
                            ImageUrl = "https://via.placeholder.com/150",
                            IsMarried = false,
                            LastName = "Winter",
                            Salary = 2500.5678m
                        },
                        new
                        {
                            Id = 9,
                            DateOfBirth = new DateTime(2004, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Description = "Description of Tom",
                            Email = "John@test.com",
                            FirstName = "Arya",
                            Gender = 0,
                            ImageUrl = "https://via.placeholder.com/150",
                            IsMarried = false,
                            LastName = "Zomer",
                            Salary = 2500.5678m
                        },
                        new
                        {
                            Id = 10,
                            DateOfBirth = new DateTime(2004, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Description = "Description of Hans",
                            Email = "Sam@test.com",
                            FirstName = "Natalie",
                            Gender = 0,
                            ImageUrl = "https://via.placeholder.com/150",
                            IsMarried = false,
                            LastName = "Winter",
                            Salary = 2500.5678m
                        },
                        new
                        {
                            Id = 11,
                            DateOfBirth = new DateTime(2004, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Description = "Description of Ceyn",
                            Email = "Ceyn@test.com",
                            FirstName = "Patricia",
                            Gender = 1,
                            ImageUrl = "https://via.placeholder.com/150",
                            IsMarried = true,
                            LastName = "Winter",
                            Salary = 2500.5678m
                        },
                        new
                        {
                            Id = 12,
                            DateOfBirth = new DateTime(2004, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Description = "Description of Donald",
                            Email = "Donald@test.com",
                            FirstName = "Silvia",
                            Gender = 0,
                            ImageUrl = "https://via.placeholder.com/150",
                            IsMarried = false,
                            LastName = "Winter",
                            Salary = 2500.5678m
                        },
                        new
                        {
                            Id = 14,
                            DateOfBirth = new DateTime(2003, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Description = "Description of John",
                            Email = "John@test.com",
                            FirstName = "John&",
                            Gender = 0,
                            ImageUrl = "https://via.placeholder.com/150",
                            IsMarried = false,
                            LastName = "Winter",
                            Salary = 2500.5678m
                        },
                        new
                        {
                            Id = 15,
                            DateOfBirth = new DateTime(2004, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Description = "Description of Sam",
                            Email = "Sam@test.com",
                            FirstName = "Sam",
                            Gender = 0,
                            ImageUrl = "https://via.placeholder.com/150",
                            IsMarried = false,
                            LastName = "Winter",
                            Salary = 2500.5678m
                        },
                        new
                        {
                            Id = 16,
                            DateOfBirth = new DateTime(2004, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Description = "Description of Ceyn",
                            Email = "Ceyn@test.com",
                            FirstName = "Ceyn",
                            Gender = 1,
                            ImageUrl = "https://via.placeholder.com/150",
                            IsMarried = true,
                            LastName = "Winter",
                            Salary = 2500.5678m
                        },
                        new
                        {
                            Id = 17,
                            DateOfBirth = new DateTime(2004, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Description = "Description of Donald",
                            Email = "Donald@test.com",
                            FirstName = "Donald",
                            Gender = 0,
                            ImageUrl = "https://via.placeholder.com/150",
                            IsMarried = false,
                            LastName = "Winter",
                            Salary = 2500.5678m
                        },
                        new
                        {
                            Id = 18,
                            DateOfBirth = new DateTime(2004, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Description = "Description of Tom",
                            Email = "John@test.com",
                            FirstName = "Tom",
                            Gender = 0,
                            ImageUrl = "https://via.placeholder.com/150",
                            IsMarried = false,
                            LastName = "Zomer",
                            Salary = 2500.5678m
                        },
                        new
                        {
                            Id = 19,
                            DateOfBirth = new DateTime(2004, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Description = "Description of Hans",
                            Email = "Sam@test.com",
                            FirstName = "Hans",
                            Gender = 0,
                            ImageUrl = "https://via.placeholder.com/150",
                            IsMarried = false,
                            LastName = "Winter",
                            Salary = 2500.5678m
                        },
                        new
                        {
                            Id = 20,
                            DateOfBirth = new DateTime(2004, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Description = "Description of Ceyn",
                            Email = "Ceyn@test.com",
                            FirstName = "Mark",
                            Gender = 1,
                            ImageUrl = "https://via.placeholder.com/150",
                            IsMarried = true,
                            LastName = "Winter",
                            Salary = 2500.5678m
                        },
                        new
                        {
                            Id = 21,
                            DateOfBirth = new DateTime(2004, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Description = "Description of Donald",
                            Email = "Donald@test.com",
                            FirstName = "Roni",
                            Gender = 0,
                            ImageUrl = "https://via.placeholder.com/150",
                            IsMarried = false,
                            LastName = "Winter",
                            Salary = 2500.5678m
                        },
                        new
                        {
                            Id = 22,
                            DateOfBirth = new DateTime(2004, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Description = "Description of Tom",
                            Email = "John@test.com",
                            FirstName = "Arya",
                            Gender = 0,
                            ImageUrl = "https://via.placeholder.com/150",
                            IsMarried = false,
                            LastName = "Zomer",
                            Salary = 2500.5678m
                        },
                        new
                        {
                            Id = 23,
                            DateOfBirth = new DateTime(2004, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Description = "Description of Hans",
                            Email = "Sam@test.com",
                            FirstName = "Natalie",
                            Gender = 0,
                            ImageUrl = "https://via.placeholder.com/150",
                            IsMarried = false,
                            LastName = "Winter",
                            Salary = 2500.5678m
                        },
                        new
                        {
                            Id = 24,
                            DateOfBirth = new DateTime(2004, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Description = "Description of Ceyn",
                            Email = "Ceyn@test.com",
                            FirstName = "Patricia",
                            Gender = 1,
                            ImageUrl = "https://via.placeholder.com/150",
                            IsMarried = true,
                            LastName = "Winter",
                            Salary = 2500.5678m
                        },
                        new
                        {
                            Id = 25,
                            DateOfBirth = new DateTime(2004, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Description = "Description of Donald",
                            Email = "Donald@test.com",
                            FirstName = "Silvia",
                            Gender = 0,
                            ImageUrl = "https://via.placeholder.com/150",
                            IsMarried = false,
                            LastName = "Winter",
                            Salary = 2500.5678m
                        });
                });

            modelBuilder.Entity("Shared.Employee", b =>
                {
                    b.HasOne("Shared.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Shared.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
